name: bump

on:
  push:
    branches:
      - main

jobs:
  bump_version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: Bump version, create changelog and publish module
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog_increment_filename: changes.md
          changelog: true
          debug: true

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - run: python -m pip install --upgrade build --user

      - run: python -m build --sdist --wheel --outdir dist/

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      - uses: softprops/action-gh-release@v1
        with:
          body_path: changes.md
          tag_name: ${{ env.REVISION }}
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
