name: publish

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'
        fetch-depth: 0
    - uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - run: >-
        python -m
        pip install --upgrade
        build
        --user
    - run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
